# Generated by Django 4.1.1 on 2022-10-27 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimepayment',
            options={'verbose_name': 'Разовый платеж', 'verbose_name_plural': 'Разовые платежи'},
        ),
        migrations.AddField(
            model_name='onetimepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
