# Generated by Django 4.1.1 on 2022-10-28 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_onetimepayment_options_onetimepayment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('start_price', models.IntegerField(verbose_name='Стартовая цена тарифа')),
                ('base_price', models.IntegerField(verbose_name='Базовая цена тарифа в неделю')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='SubscribePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.CharField(max_length=511, verbose_name='ID сохраненного метода оплаты')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный способ оплаты',
                'verbose_name_plural': 'Сохраненные способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='SubscribePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=511, verbose_name='ID платежа')),
                ('status', models.CharField(max_length=31, verbose_name='Статус платежа')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(verbose_name='Оплачено?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж тарифа',
                'verbose_name_plural': 'Платежи тарифов',
            },
        ),
        migrations.CreateModel(
            name='RateSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('start', '3 пробных дня'), ('1week', '1-ая неделя тарифа из 3'), ('2week', '2-ая неделя тарифа из 3'), ('3week', '3-я неделя тарифа из 3')], max_length=255, verbose_name='Текущий этап подписки')),
                ('step_date_expired', models.DateField(verbose_name='Дата окончания текущего этапа подписки')),
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.subscribepaymentmethod')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.ratetype')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
