# Generated by Django 4.1.1 on 2022-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ratetype_subscribepaymentmethod_subscribepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratesubscribe',
            name='report_counter',
            field=models.IntegerField(default=1, verbose_name='Оставшеейся число отчетов'),
            preserve_default=False,
        ),
    ]
