# Generated by Django 4.1.1 on 2022-11-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscribepaymentmethod_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratesubscribe',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='ratesubscribe',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='subscribepayment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscribepaymentmethod',
            name='profile',
        ),
        migrations.DeleteModel(
            name='OneTimePayment',
        ),
        migrations.DeleteModel(
            name='RateSubscribe',
        ),
        migrations.DeleteModel(
            name='SubscribePayment',
        ),
        migrations.DeleteModel(
            name='SubscribePaymentMethod',
        ),
    ]
