# Generated by Django 4.1.1 on 2022-11-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_remove_ratesubscribe_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=31, verbose_name='ID заказа')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('is_report_ready', models.BooleanField(default=False, verbose_name='Отчет составлен?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
