# Generated by Django 4.1.1 on 2022-11-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField(verbose_name='Зашифрованный токен карты')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[(0, '3 пробных дня'), (1, '1-я неделя подписки'), (2, '2-я неделя подписки'), (3, '3-я неделя плдписки')], max_length=255, verbose_name='Текущий этап подписки')),
                ('status', models.CharField(choices=[(1, 'Активна'), (-1, 'Приостановлена')], max_length=255, verbose_name='Статус подписки')),
                ('reports_counter', models.IntegerField()),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.ratetype')),
            ],
        ),
        migrations.CreateModel(
            name='RecurrentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=31, verbose_name='ID заказа')),
                ('payment_purpose', models.CharField(choices=[(0, 'Оплата 3-х дневного периода'), (1, 'Оплата 1-ой недели'), (2, 'Оплата 2-ой недели'), (3, 'Оплата 3-ей недели')], max_length=255, verbose_name='Назначение платежа')),
                ('status', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscribe')),
            ],
            options={
                'verbose_name': 'Платеж подписки',
                'verbose_name_plural': 'Платежи подписок',
            },
        ),
    ]
