# Generated by Django 4.1.1 on 2022-09-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=511, null=True, verbose_name='Вин номер')),
                ('gos_number', models.CharField(max_length=255, null=True, verbose_name='Регистрационный номер')),
                ('body_number', models.CharField(max_length=511, null=True, verbose_name='Номер кузова')),
                ('engine_number', models.CharField(max_length=511, null=True, verbose_name='Номер двигателя')),
                ('model', models.CharField(max_length=511, null=True, verbose_name='Модель')),
                ('color', models.CharField(max_length=127, null=True, verbose_name='Цвет')),
                ('year', models.CharField(max_length=16, null=True, verbose_name='Год выпуска')),
                ('engine_volume', models.CharField(max_length=127, null=True, verbose_name='Объем двигателя')),
                ('power_hp', models.CharField(max_length=31, null=True, verbose_name='Мощность л.с')),
                ('power_kwt', models.CharField(max_length=31, null=True, verbose_name='Мощность кВт.')),
                ('category', models.CharField(max_length=4, null=True, verbose_name='Категория ТС')),
                ('key', models.CharField(default=reports.models.random_value, max_length=255, unique=True, verbose_name='Уникальный ключ в базе данных')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='vehicle_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=1023, null=True, verbose_name='Регион инициатора розыска')),
                ('model', models.CharField(max_length=511, null=True, verbose_name='Марка (модель) ТС')),
                ('date', models.CharField(max_length=31, null=True, verbose_name='Дата постоянного учета в розыске')),
                ('vin', models.CharField(max_length=255, null=True, verbose_name='VIN ТС')),
                ('date_car', models.CharField(max_length=15, null=True, verbose_name='Год ТС')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_wanted')),
            ],
        ),
        migrations.CreateModel(
            name='VinDecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmi', models.CharField(max_length=255, null=True, verbose_name='WMI')),
                ('vis', models.CharField(max_length=255, null=True, verbose_name='VIS идентификатор')),
                ('vds', models.CharField(max_length=255, null=True, verbose_name='VDS')),
                ('year_identifier', models.CharField(max_length=255, null=True, verbose_name='Идентификатор года')),
                ('serial_number', models.CharField(max_length=255, null=True, verbose_name='Серийный номер')),
                ('vin_type', models.CharField(max_length=255, null=True, verbose_name='тип VIN')),
                ('body_type', models.CharField(max_length=255, null=True, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(max_length=255, null=True, verbose_name='Тип двигателя')),
                ('fuel_type', models.CharField(max_length=255, null=True, verbose_name='Тип топлива')),
                ('transmission_type', models.CharField(max_length=255, null=True, verbose_name='Тип трансмиссии')),
                ('car_class', models.CharField(max_length=255, null=True, verbose_name='Класс авто')),
                ('car_type', models.CharField(max_length=255, null=True, verbose_name='Тип авто')),
                ('body_diff', models.CharField(max_length=255, null=True, verbose_name='Отличие кузова')),
                ('number_doors', models.CharField(max_length=255, null=True, verbose_name='Кол. дверей')),
                ('number_seats', models.CharField(max_length=255, null=True, verbose_name='Кол. мест')),
                ('engine_valves', models.CharField(max_length=255, null=True, verbose_name='Кол. клапанов двигателя')),
                ('cylinders', models.CharField(max_length=255, null=True, verbose_name='Кол. цилиндров двигателя')),
                ('transmission', models.CharField(max_length=255, null=True, verbose_name='Трансмиссия')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_vindecode')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1023, null=True, verbose_name='Причина Регистрации')),
                ('owner', models.CharField(max_length=127, null=True, verbose_name='Владелец')),
                ('date_from', models.CharField(max_length=31, null=True, verbose_name='Дата регистрации')),
                ('to', models.CharField(max_length=31, null=True, verbose_name='Дата снятия с учета')),
                ('period', models.CharField(max_length=127, null=True, verbose_name='Период владения')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_periods')),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=31, null=True, verbose_name='Номер разрешения')),
                ('organization', models.CharField(max_length=511, null=True, verbose_name='Перевозчик, владелец лицензии')),
                ('date_from', models.CharField(max_length=31, null=True, verbose_name='Дата выдачи разрешения')),
                ('date_to', models.CharField(max_length=31, null=True, verbose_name='Дата окончания разрешения')),
                ('status', models.CharField(max_length=31, null=True, verbose_name='Статус разрешения')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Региональная принадлежность')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_taxi')),
            ],
        ),
        migrations.CreateModel(
            name='RNISRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_exists', models.BooleanField(default=False, null=True, verbose_name='Зарегестрировано')),
                ('last_mark', models.CharField(max_length=255, null=True, verbose_name='Дата/время передачи телематики')),
                ('is_online', models.BooleanField(default=False, null=True, verbose_name='Телематика передается')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_rnis')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=31, null=True, verbose_name='Дата отзыва')),
                ('organization', models.CharField(max_length=1023, null=True, verbose_name='Организатор')),
                ('reason', models.TextField(null=True, verbose_name='Причина отзыва')),
                ('recommendation', models.TextField(null=True, verbose_name='Рекоммендации')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_reviews')),
            ],
        ),
        migrations.CreateModel(
            name='Restrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Регион')),
                ('basis_restrict', models.TextField(null=True, verbose_name='Основание ограничения')),
                ('date_from', models.CharField(max_length=31, null=True, verbose_name='Дата наложения ограничения')),
                ('date_to', models.CharField(max_length=31, null=True, verbose_name='Дата окончания ограничения')),
                ('restrict', models.TextField(null=True, verbose_name='Вид ограничения')),
                ('who_imposed', models.CharField(max_length=511, null=True, verbose_name='Кем наложено ограничение')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_restrict')),
            ],
        ),
        migrations.CreateModel(
            name='Pledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=1023, null=True, verbose_name='Дата записи')),
                ('pledge_give', models.CharField(max_length=1023, null=True, verbose_name='Залогодатель')),
                ('pledge_give_birthday', models.CharField(max_length=63, null=True, verbose_name='Дата рождения залогодателя')),
                ('pledge_get', models.CharField(max_length=1023, null=True, verbose_name='Залогодержатель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehical_pledges')),
            ],
        ),
        migrations.CreateModel(
            name='Osago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=255, null=True, verbose_name='Серия ОСАГО')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='Номер ОСАГО')),
                ('organization', models.CharField(max_length=2047, null=True, verbose_name='Наименование страховой организации')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='Статус договора ОСАГО')),
                ('term', models.CharField(max_length=1023, null=True, verbose_name='Срок действия и период использования транспортного средства договора ОСАГО')),
                ('region', models.CharField(max_length=1023, null=True, verbose_name='Транспортное средство используется в регионе')),
                ('restrictions', models.CharField(max_length=2047, null=True, verbose_name='Договор ОСАГО с ограничениями/без ограничений лиц, допущенных к управлению транспортным средством')),
                ('action', models.CharField(max_length=511, null=True, verbose_name='Транспортное средство следует к месту регистрации или к месту проведения технического осмотра')),
                ('usage_purposes', models.CharField(max_length=1023, null=True, verbose_name='Цель использования транспортного средства')),
                ('insured', models.CharField(max_length=255, null=True, verbose_name='Страхователь')),
                ('owner', models.CharField(max_length=255, null=True, verbose_name='Собственник')),
                ('date_actual', models.CharField(max_length=31, null=True, verbose_name='Дата актуальности')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_osago')),
            ],
        ),
        migrations.CreateModel(
            name='Dtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=31, null=True, verbose_name='Дата ДТП')),
                ('damage', models.CharField(max_length=1023, null=True, verbose_name='Повреждения')),
                ('type', models.CharField(max_length=1023, null=True, verbose_name='Тип ДТП')),
                ('damage_description', models.TextField(null=True, verbose_name='Описание инцидента')),
                ('place', models.CharField(max_length=255, null=True, verbose_name='Место ДТП')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_dtp')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsExpired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=31, null=True, verbose_name='Дата начала ДК')),
                ('expire_date', models.CharField(max_length=31, null=True, verbose_name='Дата окончания ДК')),
                ('value', models.CharField(max_length=31, null=True, verbose_name='Показания одометра')),
                ('dc_number', models.CharField(max_length=31, null=True, verbose_name='Номер ДК')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_diagnostic_expired')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=31, null=True, verbose_name='Дата выдачи ДК')),
                ('expire_date', models.CharField(max_length=31, null=True, verbose_name='Дата окончания ДК')),
                ('value', models.CharField(max_length=31, null=True, verbose_name='Показания одометра')),
                ('dc_number', models.CharField(max_length=31, null=True, verbose_name='Номер ДК')),
                ('point_address', models.CharField(max_length=511, null=True, verbose_name='Адрес выдачи ДК')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_diagnostic_active')),
            ],
        ),
        migrations.CreateModel(
            name='CustomsClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('date', models.CharField(max_length=255, null=True, verbose_name='Дата выпуска в свободное обращение')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_customs')),
            ],
        ),
    ]
