# Generated by Django 4.1.1 on 2022-09-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='car_photos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vehicle', verbose_name='vehicle_image')),
            ],
        ),
    ]
