# Generated by Django 4.1.1 on 2022-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
