# Generated by Django 4.1.1 on 2022-09-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_vehicle_date_actual_vehicle_is_full_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_actual',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата составления отчета'),
        ),
    ]
