# Generated by Django 4.1.1 on 2022-09-29 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_alter_vehicle_date_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='vehicle_profiles'),
        ),
    ]
